# fly.toml app configuration file generated for 3d-dekor on 2025-01-24T15:54:12+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = '3d-dekor'
primary_region = 'fra'

[build]

[http_service]
internal_port = 8000
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '1024mb'
cpu_kind = 'shared'
cpus = 1
